stages:
#  - test
  - deploy

#.test_package: &test_package
#  image: node:10-alpine
#  stage: test
#  script:
#    - npm install -g npm-cli-login
#    - npm-cli-login
#    - npm i
#    - npm test

.publish_package: &publish_package
  image: node:10-alpine
  stage: deploy
  script:
    - npm install -g npm-cli-login
    - npm-cli-login
    - npm i
    - npm run build
    - npm publish

# test package
#Test Package:
#  <<: *test_package
#  only:
#    - tags

# build package and push to npm
Publish Package:
  <<: *publish_package
  only:
    - tags
    - triggers
