stages:
  - build
  - test
  - deploy

image: node:12-alpine

.cache:
  cache:
    paths:
      - lib
      - node_modules

.only_tags:
  only:
    - tags

.build:
  extends: .cache
  cache:
    policy: push
  stage: build
  script:
    - npm install -g npm-cli-login
    - npm-cli-login
    - npm ci
    - npm run build

.test:
  extends: .cache
  cache:
    policy: pull
  stage: test
  script:
    - npm run test

.publish:
  extends: .cache
  cache:
    policy: pull
  stage: deploy
  script:
    - npm install -g npm-cli-login
    - npm-cli-login
    - npm publish

# build package and push to npm
Build:
  extends:
    - .build
    - .only_tags

Test:
  extends:
    - .test
    - .only_tags

Publish:
  extends:
    - .publish
    - .only_tags
